### ISSUE TITLE
Request for lcov.info supported output format

### ISSUE THREAD

**Issue by jbenden** [parroty/excoveralls#104]
I would like to see `lcov.info` as a supported output.

It would permit my editor, VS Code, to visualize the code coverage detail graphically within the editor.

Thanks!

**Comment by nathany** [comment]
It would also be nice if excoveralls support LCOV to support multiple test suites (e.g. Elixir + JavaScript).

However, LCOV doesn't appear to be a documented format, so I'm not sure how difficult it will be to add support.

It's not clear to me what all these things mean:

```
FN:12,App
FNF:1
FNH:1
FNDA:1,App
DA:13,1
LF:1
LH:1
BRF:0
BRH:0
end_of_record
```

Has anyone located documentation on the file format?

**Comment by nathany** [comment]
|----|---------------------|
| TN | title |
| SF | source file |
| FNF | functions found |
| FNH | functions hit |
| LF | lines found |
| LH | lines hit |
| DA | line details |
| FN | functions details? |
| FNDA | functions details? |
| BRDA | branch details? |
| BRF | branches found |
| BRH | branches hit |

Based on reading this: https://github.com/davglass/lcov-parse/blob/master/lib/index.js

**Comment by nathany** [comment]
Rust has some documentation on the LCOV format: https://github.com/mitchhentges/lcov-rs/wiki/File-format#lcov-info-file-output-of-lcov-rs

**Comment by Maxim-Filimonov** [comment]
For vscode specific use case - run lcov locally and coveralls on CI there is a workaround:
```
test_coverage: if(System.get_env("CI"), do: [tool: ExCoveralls], else: [tool: LcovEx, output: "cover"])
```
Using [Lcov_Ex pkg](https://hexdocs.pm/lcov_ex/readme.html )

**Comment by satoren** [comment]
I'm using lcov support version with below services. It's working fine.


* [code-coverage-action (Github Actions)](https://github.com/barecheck/code-coverage-action)
* [Coverage Gutters (VSCode extension)](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters)

**Comment by Maxim-Filimonov** [comment]
@satoren Great contribution 👍 Works for me too, can simplify our setup now.
