### ISSUE TITLE
Ignore files/directory?

### ISSUE THREAD

**Issue by PragTob** [parroty/excoveralls#109]
:wave:

For reasons unbeknown to me the coverage report includes one (and only one file!) from postgrex:

```
tobi@liefy ~/projects/bla $ mix coveralls.html

14:11:47.392 [info]  Already up
......................................................................................................................................................

Finished in 3.3 seconds
150 tests, 0 failures

Randomized with seed 319256
----------------
COV    FILE                                        LINES RELEVANT   MISSED
 30.0% deps/postgrex/lib/postgrex/type_module.e      718       10        7
# MORE
````

is there any way to ignore files? I couldn't find anything in the README and I see how this might be doen through the lower level Erlang `cover` library but [the docs](http://erlang.org/doc/apps/common_test/cover_chapter.html) only ever speak of "the cover specification file" but don't mention where to put it (or I couldn't find it) - found a stakcoverflow and tried: 

```
tobi@liefy ~/projects/project_root $ cat cover.spec 
 {excl_dirs_r, ["deps"]}.
```

But to no avail. 

Any help highly appreciated, thanks for the project!
Tobi

**Comment by parroty** [comment]
Thanks for the description. The following option can be used for your case?
- https://github.com/parroty/excoveralls#exclude-files

**Comment by PragTob** [comment]
:see_no_evil: 

How I missed that in the README is beyond me. I swear I ctrl + f'ed, and did google searches but always for "ignore" not for exclude which is my mistake.

So so very sorry :| Thanks for your help :green_heart:
