### ISSUE TITLE
Don't fail the build when uploading the report times out

### ISSUE THREAD

**Issue by PragTob** [parroty/excoveralls#112]
:wave: 

It has happened a couple of times to me now that my build failed because uploading the coverage report timed out:

```
** (ExCoveralls.ReportUploadError) Failed to upload the report to 'https://coveralls.io' (reason: timeout).

    lib/excoveralls/poster.ex:20: ExCoveralls.Poster.execute/2

    (mix) lib/mix/tasks/test.ex:244: Mix.Tasks.Test.run/1

    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3

    lib/mix/tasks.ex:51: Mix.Tasks.Coveralls.do_run/2

    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3

    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

    (elixir) lib/code.ex:363: Code.require_file/2
```

It'd be nice (imo) if that didn't break the build or if there was an option to make it not break the build and be just like "go on, I can go without coverage information from one build" and just print a warning.

I.e. in [this build 2/8 gailed](https://travis-ci.org/PragTob/benchee/builds/268498345?utm_source=github_status&utm_medium=notification) and [here 1/8 failed](https://travis-ci.org/PragTob/benchee/builds/268498133?utm_source=github_status&utm_medium=notification)

I hope I didn't miss an option that already does this again ;)

I know optimally it wouldn't time out, but it does :D 

Happy to send a PR if it's agreed how to do this :)

**Comment by vorce** [comment]
I'm running into this issue now and then, it's getting a bit annoying. Would like to avoid adding custom task wrappers to all our projects.

**Comment by parroty** [comment]
Closing for 173 merge.
