### ISSUE TITLE
Move from ExJSX to Poison

### ISSUE THREAD

**Issue by BenMorganIO** [parroty/excoveralls#118]
Yo, just stopping by again to post another issue about dependencies. Apologies.

Anywho, I noticed that Excoveralls has exjsx is used for encoding and decoding JSON. Is it possible to move from exjsx to poison? In my current project, excoveralls is the only one using exjsx which depends on jsx and poison has no dependencies. Ecto and Phoenix also rely on poison.

**Comment by KronicDeth** [comment]
Ecto and Phoenix are moving from Poison to Jason, so go to Jason, not Poison.

**Comment by parroty** [comment]
Thanks for the comments. v0.9.0 or later is working wth Jason.
- https://github.com/parroty/excoveralls/releases/tag/v0.9.0
