### ISSUE TITLE
Unable to make this work under an umbrella app

### ISSUE THREAD

**Issue by naps62** [parroty/excoveralls#145]
When running with `mix coveralls.json --umbrella`, I do get the output showing the coverage of each app, but the overall umbrella summary is 0.0%, and the top-level `cover/excoveralls.json` file is empty

I need to grab the full summary and submit to codecov.io (done outside of excoveralls, but uploading the result file directly).

But apparently, the combination of umbrella app + not using coveralls.io doesn't seem to work

I was also looking through the code, and found that in `lib/excoveralls:33`, the call to `ConfServer.get()` apparenlty isn't fetching the real configs, which makes the entire execution not do what it is suposed to. Is this running on a different BEAM process that doesn't have access to the same ETS table?

Running ConfServer.get() here, and in the mix task code seems to provide different results

**Comment by parroty** [comment]
The simplest form of example is in the following. Is there any specific condition to note? or which `excoveralls` version is applied?
- https://github.com/parroty/excoveralls_umbrella

**Comment by Kartstig** [comment]
I'm also getting this error:

mix.exs:
```elixir
...
{:excoveralls, "~> 0.10", only: [:test], runtime: false},
...
```

here's my output:
```
{"source_files":[]}
```

**Comment by Kartstig** [comment]
I was able to fix this by reading the docs. D'oh!

<img width="791" alt="Screen Shot 2019-03-08 at 2 33 53 PM" src="https://user-images.githubusercontent.com/2031422/54051216-438e6b00-41af-11e9-8995-4535906d655d.png">
