### ISSUE TITLE
coveralls.post doesn't recognize mix test options 

### ISSUE THREAD

**Issue by purbanow** [parroty/excoveralls#156]
Helllo folks! 

I have a problem passing mix test options to mix coveralls.post.

Example:
`mix coveralls  --no-start --umbrella --include integration` - it is working perefctly as I expected. 

`mix coveralls.post  --no-start --umbrella --include integration --token ''  --sha '' ` It doesn't recognize `--no-start` and `--include` options. 

Is it a bug or am I doing something wrong ? 
Thanks

**Comment by vorce** [comment]
Ah yes.. looks like the post task is dropping unknown args. I think there are some refactoring opportunities in the `Mix.Tasks.Coveralls` module to fix this issue nicely. I might take a stab at it..

**Comment by vorce** [comment]
@purbanow Oh, interesting. I'll take a look!

**Comment by vorce** [comment]
@purbanow I've added another commit to my PR to try and fix that

**Comment by purbanow** [comment]
@vorce it's working now. Thanks a lot for the fix!
