### ISSUE TITLE
Is there any jenkins plugin compatible with this?

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [parroty/excoveralls#167]
I was wondering if this code report can be used by Jenkins CI. Since I didn't find any Coveralls Plugin I assume it cant't so I just wanted to make sure.

**Comment by shanesveller** [comment]
Also shared on the Elixir Forum, but in case anyone turns up here from a search:

> Try using a [JUnit Formatter](https://github.com/victorolinasc/junit-formatter) Elixir package together with the `junit` [pipeline step](https://jenkins.io/doc/pipeline/tour/tests-and-artifacts/) in your Jenkinsfile.
