### ISSUE TITLE
Feature request: Add mix test options

### ISSUE THREAD

**Issue by TattdCodeMonkey** [parroty/excoveralls#17]
Currently there is not a way to pass options to the test task. `mix test` has [several options](http://elixir-lang.org/docs/stable/mix/Mix.Tasks.Test.html). 

Of particular interest to me is the `--no-start` option to run tests without starting the Application.

**Comment by parroty** [comment]
Thank for the comment. I don't have much time right now, but I'll be checking.

**Comment by parroty** [comment]
I didn't have good example for `--no-start` and tried with `--seed` and `--trace`. Please reopen if there's any missing point.

**Comment by TattdCodeMonkey** [comment]
This worked great, thanks!!!

**Comment by vorce** [comment]
Hmm, I'm still not being able to pass `--no-start` to excoveralls. I run `MIX_ENV=test mix coveralls.html --no-start`, but my application still gets started. Looking closer it seems the args value in https://github.com/parroty/excoveralls/blob/master/lib/mix/tasks.ex#L47 is empty. 

I can investigate more and maybe send a PR next week.

**Comment by parroty** [comment]
Thanks for the PR (#50).
