### ISSUE TITLE
Compile error when running mix coveralls

### ISSUE THREAD

**Issue by grufino** [parroty/excoveralls#181]
I'm getting this error when trying to run the task mix coveralls.
```
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: :error
        cover.erl:1580: :cover.do_compile_beam2/5
        cover.erl:1480: :cover.do_compile_beam/3
        (stdlib) lists.erl:1239: :lists.map/2
        cover.erl:2795: anonymous fn/2 in :cover.pmap_spawn/4
    cover.erl:585: :cover.call/1
    lib/excoveralls/cover.ex:12: ExCoveralls.Cover.compile/1
    lib/excoveralls.ex:32: ExCoveralls.start/2
    (mix) lib/mix/tasks/test.ex:351: Mix.Tasks.Test.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    lib/mix/tasks.ex:54: Mix.Tasks.Coveralls.do_run/2

10:03:50.512 [error] Process #PID<0.4329.0> raised an exception
** (MatchError) no match of right hand side value: :error
    cover.erl:1580: :cover.do_compile_beam2/5
    cover.erl:1480: :cover.do_compile_beam/3
    (stdlib) lists.erl:1239: :lists.map/2
    cover.erl:2795: anonymous fn/2 in :cover.pmap_spawn/4
```

I have 3+ applications using this same setup for coveralls and in all of them it works. The only difference in this one is that I don't have HTML because it's only rest api, but even when I try to remove the coveralls html task it doesn't work. It seems to be something with compiling in erlang :cover but I tried to debug and it is pointing to the right directory.

This is my Mix file:

```
defmodule Tow.MixProject do
  use Mix.Project

  def project do
    [
      app: :tow,
      version: "0.1.0",
      elixir: "~> 1.8",
      compilers: [:phoenix] ++ Mix.compilers(),
      start_permanent: Mix.env() == :prod,
      test_coverage: [tool: ExCoveralls],
      preferred_cli_env: [
        coveralls: :test,
        "coveralls.detail": :test,
        "coveralls.post": :test,
        "coveralls.html": :test
      ],
      elixirc_paths: elixirc_paths(Mix.env()),
      deps: deps(),
      aliases: aliases()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger, :plug_cowboy],
      mod: {Tow.Application, []}
    ]
  end

  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_), do: ["lib"]

  defp deps do
    [
      {:phoenix, "~> 1.4"},
      {:flow, "~> 0.14"},
      {:timex, "~> 3.1"},
      {:math, "~> 0.3.0"},
      {:plug_cowboy, "~> 2.0"},
      {:poison, "~> 3.1"},
      {:ecto_sql, "~> 3.0"},
      {:mariaex, "~> 0.8"},
      {:statistics, "~> 0.5.0"},
      {:elixir_uuid, "~> 1.2"},
      {:ex_aws, "~> 2.1"},
      {:ex_aws_s3, "~> 2.0"},
      {:config_tuples, "~> 0.2.0"},
      # dev / test
      {:benchee, "~> 1.0", only: :dev},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:ex_machina, "~> 2.2.2", only: :test},
      {:faker, "~> 0.10", only: :test},
      {:excoveralls, "~> 0.10", only: :test}
    ]
  end

  # Aliases are shortcuts or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    [
      "ecto.setup": ["ecto.create", "ecto.load", "ecto.migrate"],
      "ecto.reset": ["ecto.drop", "ecto.setup"],
      test: ["ecto.create --quiet", "ecto.migrate", "test"]
    ]
  end
end
```

**Comment by grufino** [comment]
The issue was with erlang Cover library, I had a TypeSpec in one of my modules that for some reason could not be compiled.

**Comment by ccapndave** [comment]
I also ran into this error; it was caused specifically by using `__MODULE__` in a typespec, which Dialyzer seemed happy with but Coveralls didn't.

**Comment by grufino** [comment]
Hmmm strange because I didn't use this syntax in my typespec that generated
the error:
@spec get_basepoint(nil | {float(), float()}, [any()], [any()]) :: Tow.
Accounts.Basepoint.t()

**Comment by jeroenbourgois** [comment]
I am facing the same issue, but it seems hard to find the root cause. Any tips @grufino to find the culprit?

**Comment by grufino** [comment]
Hey guys, it was very difficult and manual to find the bug, I started literally deleting folders, checking if the error stopped, if not I restored and try delete another folder but from the bottom... When I found the folder with problem, deleting file by file the same way, and then I eventually found out it was the typespec in one file when deleting functions...

**Comment by ymtszw** [comment]
I encountered this issue and investigated.
At the end of the day I found that it was due to non-existent type `MyModel.t()` being mentioned in typespecs, where `MyModel` was an `Ecto.Schema`.

As discussed in https://elixirforum.com/t/adding-typespect-to-an-ecto-schema/3180,
and also in https://github.com/elixir-ecto/ecto/issues/425,
`Ecto.Schema` model modules DO NOT automatically generate their types `t()`. The feature was discussed, but eventually closed due to its implementation complexities. See the issues above for details.

To make matters worse, mentioning `MyModel.t()` does not usually make dialyzer to bark since `MyModel` contains many `Ecto.Schema` macros manipulating ASTs which confuses dialyzer (at least I assume so.)

To fix this issue, you should carefully remove or actually define missing types found in typespecs in your code. `Ecto.Schema` model modules are good candidates to search for.

**Comment by lukaszsamson** [comment]
I also stumbled on this error in a codebase that compiles and dialyzes fine. I was able to pinpoint it to be caused by elixir generating invalid typespec for macro with when (https://github.com/elixir-lang/elixir/issues/9687)
e.g.
```
@spec some(b) :: Macro.t() when b: float
defmacro some(var), do: Macro.expand(var, __CALLER__)
```
or
```
@macrocallback optional(a) :: Macro.t() when a: atom
```
