### ISSUE TITLE
Problem Using ExCoveralls When There Are Specs In Code

### ISSUE THREAD

**Issue by dc0d** [parroty/excoveralls#187]
In short, when the specs are removed from  `lib/excoveralls_spec_lab/kata/user.ex` , then the command  `mix coveralls.html`  works without a problem and generates the output html file  `cover/excoveralls.html` .

But if there are any specs in  `lib/excoveralls_spec_lab/kata/user.ex` , then the command  `mix coveralls.html`  will show this error:

```
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: :error
        cover.erl:1591: :cover.do_compile_beam2/6
        cover.erl:1483: :cover.do_compile_beam/3
        (stdlib) lists.erl:1239: :lists.map/2
        cover.erl:2911: anonymous fn/2 in :cover.pmap_spawn/4
    cover.erl:600: :cover.call/1
    lib/excoveralls.ex:32: ExCoveralls.start/2
    (mix) lib/mix/tasks/test.ex:351: Mix.Tasks.Test.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    lib/mix/tasks.ex:54: Mix.Tasks.Coveralls.do_run/2
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

Sample repository for reproducing the issue can be found [here](https://github.com/dc0d/excoveralls_spec_lab).

**Comment by Eiji7** [comment]
@dc0d That's weird, because it behaves differently for me …

> (…) when the specs are removed (…) the command mix coveralls.html works without a problem (…)

After cloning your repository, fetching deps and calling `mix coveralls.html` I got that error, but when I opened this file I found that there are no type defined …

I tried to add type like:

```elixir
@type t :: %__MODULE__{friends: list(), trips: list()}
```

and after it `mix coveralls.html` command works as expected …

Here is my environment:
```bash
$ asdf current
elixir         1.8.2-otp-22 (set by …)
erlang         22.0.3   (set by …)
```

**Comment by dc0d** [comment]
Thanks for the reply! I'll try that one.

The `.tool-versions` is different in the provided sample repo:

```
erlang 22.0.1
elixir 1.8.2
```

**Comment by Eiji7** [comment]
@dc0d Yup, I'm using `Erlang 22.0.3`, because wanted to tried it fast (in `asdf` every `Erlang` install is compiled which takes some time for me) and `Elixir 1.8.2-otp-22`, because it's precompiled release for specific otp release. I have tried and got same results on `Elixir 1.9.0-rc.0-otp-22`. I will try this on different `Erlang` releases too soon.

**Comment by dc0d** [comment]
I have added `dialyxir` and tried it out, and it shows this error `Unknown type`:

```
Compiling 4 files (.ex)
Generated excoveralls_spec_lab app
Checking PLT...
[:compiler, :elixir, :kernel, :logger, :stdlib]
Finding suitable PLTs
...
done in 0m1.36s
:0: Unknown type 'Elixir.ExcoverallsSpecLab.Kata.Trip':t/0
:0: Unknown type 'Elixir.ExcoverallsSpecLab.Kata.User':t/0
done (warnings were emitted)
```

**Comment by Eiji7** [comment]
@dc0d For sure this error message is not clear and it would be really nice if somebody would fix it, but it's not especially related to `excoveralls` itself.

Look that to generate docs, coverage information etc. you need to firstly make your project compilable. Fortunately `Elixir` covers all compile errors, but `excoveralls` is not a part of `Elixir` core and does not cover any part of project compilation. More! Without compiled project it would not even run. It has nothing to do with type checking. As `ex_doc` assumes (and don't check it in any way) that project is able to compile and code examples are valid as same `excoveralls` assumes that whole project is valid and coverage could be generated.

Also it potentially could be a problem to ensure that all documentation-related errors are handled in `excoveralls`. Look that `dialyxir` (and its dependencies) are not projects with "10 lines of code", so basically you would need to implement (at least part of) `dialyzer`/`dialyxir` features which has no sense.

In my opinion you should just run tools in right order, so you should not hit any edge-case like that one. I have used `excoveralls` lots of times and while I can see that it could be much improved I still did not get such error previously.

Here is example list of tasks order:
1. `mix deps.get` - without deps project would not compile
2. `mix compile` - without compilation we can't generate docs and coverage
3. `mix dialyzer` - without proper analyse we could have some documentation problems (like here)
4. `mix test` - without tests documentation could be incorrect as tests in it could fail
5. `mix docs` and `mix coveralls.html` - those tasks assumes that code and it's documentation has no errors
6. `mix hex.publish` or `mix release` - final tasks

**Comment by dc0d** [comment]
Since `mix test` was working, I thought everything if fine. :)

**Comment by lukaszsamson** [comment]
https://github.com/parroty/excoveralls/issues/181#issuecomment-572812796
