### ISSUE TITLE
Add documentation about defaulting to env :dev

### ISSUE THREAD

**Issue by zmoshansky** [parroty/excoveralls#21]
Thanks for the great work here!

It may be worth documenting that the `mix coveralls` command doesn't run in the :test env by default. I mention this as I got some failing tests while running coveralls due to the :dev database having extra content. 

Of course `MIX_ENV=test mix coveralls` is a very easy solution, but worth mentioning explicitly in the readme. As a beginner with elixir this would be very helpful.

**Comment by parroty** [comment]
Thanks for the comment. 
> I got some failing tests while running coveralls due to the :dev database having extra content.

Could you describe this point a little more? How your mix file is configured?

**Comment by zmoshansky** [comment]
What I mean is that my dev database has all sorts of records in it. But, some of the tests phoenix generates fail when that data is present.

ex.) `refute Repo.all(User)` may fail if I have a user and my test expected an empty users table.

Regardless, it seems like the documentation should suggest to run `MIX_ENV=test mix coveralls` because otherwise tests could accidentally destroy the dev database which would be pretty unexpected.

**Comment by parroty** [comment]
Thanks for the information!
