### ISSUE TITLE
Github Actions for excoveralls repository fail

### ISSUE THREAD

**Issue by mijailr** [parroty/excoveralls#211]
The test for excoveralls itself in github actions are failing because the capure_io is not working properly.

To be precise:

- test/html_test.exs#L69
- test/local_test.exs#L88

Both has assertions on error status codes causing the failure, how we fix it?

The pull request #210 has a failure status related to this issue.

**Comment by parroty** [comment]
Sorry, I don't have clear answer at the moment, but please let me disable the github action at the moment (until this can be resolved).

This repository itself is tested on travis, and I think it can be separated from the general github actions feature support.

**Comment by parroty** [comment]
Revisited this item in the above mentioned PR (though it took long time...). The analysis in this issue and the PR helped isolating problems, thank you!
I'm closing this item, but if you find any remaining issue, please re-open.
