### ISSUE TITLE
feature request: ignore one line

### ISSUE THREAD

**Issue by samm81** [parroty/excoveralls#219]
Using phoenix, I find that many `use` statements get tagged as not tested eg `use MyAppWeb, :view`

It would be nice to have the ability to ignore just the next line, eg `# coveralls-ignore-next-line`

Otherwise my formatter ends up spacing out the comments so what could be two lines takes five:

```elixir
# coveralls-ignore-start

use MyAppWeb, :view

# coveralls-ignore-stop
```

Just a small thing. Thank you for all your work on this project!

**Comment by jenskdsgn** [comment]
👍

Thanks @RKushnir for the implementation, I'd love to see this getting merged :)
