### ISSUE TITLE
Use Cobertura format for XML output

### ISSUE THREAD

**Issue by hauleth** [parroty/excoveralls#245]
Right now it uses format that seems custom for this project, which mean that it is unusable with tools that expect Cobertura output like GitLab CI reporting.

**Comment by peake100** [comment]
+1 on this

**Comment by gleopoldo** [comment]
Hello!
I am using azure devops here as well, and I couldn't yet find a solution for coverage results publishing yet. Is there any workaround for this?

**Comment by hauleth** [comment]
@gleopoldo use [`covertool`](https://github.com/covertool/covertool)

**Comment by gorghoa** [comment]
@hauleth, thanks to @albertored recent work, since version `0.16`, the task `coveralls.cobertura` is now out! (I use it too with gitlab ci).

see #302
