### ISSUE TITLE
String interpolations seem to confuse excoveralls

### ISSUE THREAD

**Issue by flupke** [parroty/excoveralls#26]
See: https://coveralls.io/builds/3214121/source?filename=lib%2Fexdatauri.ex

Line 155 for example was executed by the tests.

**Comment by parroty** [comment]
Thanks for several reports with example. I'll be busy during the week and try to look up over the weekend. Some of the elixir-unique syntax is not well reported by erlang cover, but there might work around for some of them.

**Comment by lpil** [comment]
Hello!

I think I have the same problem here -> https://coveralls.io/builds/3374218/source?filename=lib%2Fmix%2Ftasks%2Fdogma%2Frules_list.ex

**Comment by parroty** [comment]
I'm sorry taking time. Is this related to the following item, correct?
https://github.com/elixir-lang/elixir/issues/3444

**Comment by sunaku** [comment]
It seems elixir-lang/elixir#3444 has been marked as fixed for Elixir milestone v1.1.0. :tada:

So all we need to do is wait for the official Elixir 1.1.0 release to solve this issue! :smiley_cat:

**Comment by parroty** [comment]
I'm closing this item as it seems fixed as in the above issue item (checked with v1.2).
