### ISSUE TITLE
Coverage report drops between Elixir-1.11.4 and 1.12.1

### ISSUE THREAD

**Issue by mad42** [parroty/excoveralls#260]
both tests were running on OTP-24.0.2
coverage total % differs between

**elixir 1.11.4 :** [TOTAL]  98.6%
**elixir 1.12.1 :** [TOTAL]  95.8%

Any idea what's causing this drop in percentage ?

**Comment by johnf9896** [comment]
That happened to me too. If you compare the generated HTML's, you can see the number of lines taken as significant increased. No idea why they did, though.
