### ISSUE TITLE
Support --warnings-as-errors option

### ISSUE THREAD

**Issue by Serabe** [parroty/excoveralls#291]
It'd be great if we could pass the option --warnings-as-errors to `mix test`.

Thank you!

**Comment by mwhitworth** [comment]
You can pass `--warnings-as-errors` already - arguments are forwarded to `mix test`

**Comment by RKushnir** [comment]
@Serabe does the previous comment answer your question and so this issue can be closed?
cc: @parroty

**Comment by Serabe** [comment]
I'm in a new project and it's working wonderfully. Not sure why it was not working correctly in my previous project as I no longer has access to it. Closing it.

Thank you so much for your work.
