### ISSUE TITLE
0% coverage for 0 missed lines

### ISSUE THREAD

**Issue by sunaku** [parroty/excoveralls#32]
Hello,

I'm using Elixir 1.1.1 with Erlang 18.1 and ExCoveralls 0.3.11 under 64-bit Linux.

The problem is that 0% coverage is reported for a file with 0 missed lines: :scream:

```
COV    FILE                                        LINES RELEVANT   MISSED
  0.0% lib/-----------------------------.ex           40        0        0
```

Shouldn't this be 100% coverage?  :cold_sweat:

Thanks for your consideration.

**Comment by parroty** [comment]
Thanks for trying out. I think it's related to https://github.com/parroty/excoveralls/pull/7. Please try the option setting.

**Comment by parroty** [comment]
I'm closing at the moment, but if there's the above option doesn't work well, please reopen.

**Comment by sunaku** [comment]
Thanks, setting "treat_no_relevant_lines_as_covered" worked. :+1:
