### ISSUE TITLE
** (UndefinedFunctionError) undefined function: __info__/1

### ISSUE THREAD

**Issue by sunaku** [parroty/excoveralls#33]
Hello,

I'm using excoveralls 0.4.0 with Elixir 1.1.1 and Erlang 18.1 under 64-bit Linux. :smiley:

[Following this guide](http://andrealeopardi.com/posts/tokenizing-and-parsing-in-elixir-using-leex-and-yecc/), I created a `src/Elixir.My.List.Lexer.xrl` file containing:

```erlang
Definitions.

INT        = [0-9]+
ATOM       = :[a-z_]+
WHITESPACE = [\s\t\n\r]

Rules.

{INT}         : {token, {int,  TokenLine, list_to_integer(TokenChars)}}.
{ATOM}        : {token, {atom, TokenLine, to_atom(TokenChars)}}.
\[            : {token, {'[',  TokenLine}}.
\]            : {token, {']',  TokenLine}}.
,             : {token, {',',  TokenLine}}.
{WHITESPACE}+ : skip_token.

Erlang code.

to_atom([$:|Chars]) ->
    list_to_atom(Chars).
```

Afterwards, I get the following error when running `mix coveralls`: :scream:

```sh
$ MIX_ENV=test mix coveralls
Compiled src/Elixir.My.List.Lexer.xrl
Compiled src/Elixir.My.List.Lexer.erl
...
72 tests, 0 failures

Randomized with seed 236840
** (UndefinedFunctionError) undefined function: My.List.Lexer.__info__/1
    (yield) My.List.Lexer.__info__(:compile)
    lib/excoveralls/cover.ex:19: ExCoveralls.Cover.module_path/1
    lib/excoveralls/stats.ex:36: ExCoveralls.Stats.add_counts/4
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/excoveralls/stats.ex:11: ExCoveralls.Stats.report/1
    lib/excoveralls.ex:29: ExCoveralls.execute/2
    (mix) lib/mix/tasks/test.ex:198: Mix.Tasks.Test.run/1
    lib/mix/tasks.ex:43: Mix.Tasks.Coveralls.do_run/2
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2

exit 1
```

See also https://github.com/elixir-lang/ex_doc/issues/453 :hamster: 

Thanks for your consideration.

**Comment by parroty** [comment]
Thanks for the report. `excoveralls` is using the `__info__` function of module to retrieve the source code information for the module, and it may be causing the error. 

Do you have any expectation how it needs to be fixed? Checking if `__info__` is available and skip the module (excluding it just for avoiding error) makes sense?

**Comment by sunaku** [comment]
Yes, that makes sense. :+1:  Maybe you could print a warning too, so that users are aware of the missing `__info__` (which is normal for Erlang modules) just in case they are doing unconventional things like this.

**Comment by parroty** [comment]
Thanks. That makes sense. I'll try to work on the weekend.
What I'm not sure is the proper way of checking the condition (normal way would be to use `Module.__info__[:functions]` which is not available for this case, and `Module.definitions_in(module)` seems available at runtime). Try/Rescue can be the easiest way though.

**Comment by parroty** [comment]
I could simulate the error in my local environment, and tried to skip the module if `__info__/1` is not available (along with warning message). 
I'm closing at the moment, but if you find any remaining issue, please reopen or open another one.

**Comment by sunaku** [comment]
Works great! :+1: Thank you. :bow:
