### ISSUE TITLE
Exit with status 1 when coverage drops below a configurable threshold

### ISSUE THREAD

**Issue by campezzi** [parroty/excoveralls#43]
It would be great to have Mix tasks like `mix coveralls` or `mix coveralls.html` to exit with status 1 when coverage drops below a user-defined level on `local` tasks. That would be useful to interrupt CI pipelines, for instance.

I'd be glad to help implement this. I took a quick look at the code and it seems most stats are totalled in the `ExCoveralls.Local` module. Seems like it would be easy to expose a function there that returns the totals, then use those to get the percentage on the mix task and exit with status 1 if it's below something defined in the `coveralls.json` file. On the other hand, it may be worth refactoring some of the calculations that go on in `ExCoveralls.Local` so they happen in `ExCoveralls.Stats` instead (with `Local` invoking those to compose output).

Let me know what you think the best approach is and I can take a stab at it!

**Comment by parroty** [comment]
Thanks for the comment. The functionality sounds good (as long as it's optional setting). PR is appreciated :smile: 
As you indicated, some refactoring might be required, as the current calculation logic is mixed into the display logics...

**Comment by campezzi** [comment]
Added a PR - I haven't refactored everything that could be refactored yet, but it's a start :)

**Comment by parroty** [comment]
I'm closing with the PR merge, but if there's any remaining item, please reopen.
