### ISSUE TITLE
--include tags

### ISSUE THREAD

**Issue by nathany** [parroty/excoveralls#46]
My test helper has the following line to exclude tests that hit remote services by default:

```
ExUnit.configure(exclude: [:remote])
```

When I want remote tests I run:

```
mix test --include remote
```

What is the equivalent for `mix coveralls`?

**Comment by nathany** [comment]
Somone on Slack told me to do: 

```
mix test --include remote --cover
```

That works, and would work around the issue in #47 if `test_coverage: [tool: ExCoveralls]` can be configured to generate an HTML report.

**Comment by campezzi** [comment]
I believe changing "local" to "html" in [this line](https://github.com/parroty/excoveralls/blob/master/lib/excoveralls.ex#L38) will do what you want. I'll try to take some time over the weekend to make that configurable via the `coveralls.json` file!

**Comment by campezzi** [comment]
Maybe running this will work:
```
mix excoveralls.html --include remote
```
I took a quick look at the code for the `excoveralls.html` mix task and it seems to forward its arguments to the test task, so this might be enough.

**Comment by nathany** [comment]
@campezzi Nope.

> 201 tests, 0 failures, 17 skipped

It would be much more intuitive if excoveralls supported the --include, --exclude, and --only flags.

**Comment by parroty** [comment]
I'm sorry being late to respond. Does it relate to #50?

**Comment by nathany** [comment]
It sounds like #50 may fix this, yah.

**Comment by leifg** [comment]
I just tested it and didn't get this to work (on 0.5.4):

    MIX_ENV=test mix coveralls.html --only slow

executes all the tests I have and completely ignores my options.

**Comment by nathany** [comment]
Yah, it's still not working for me either. To run all the coverage I need to comment out this line from my test_helper because I can't specify `--include remote` on the command line.

```
ExUnit.configure(exclude: [:remote])
```

**Comment by nathany** [comment]
The patch in #50 doesn't quite work. Args goes from `["--include", "remote"]` to `[{"--include", nil}]`. See invalid here: http://elixir-lang.org/docs/stable/elixir/OptionParser.html#parse/2

I'm working on a fix.

**Comment by nathany** [comment]
To be honest, it seems like #50 is the reason this doesn't work -- as compared to the previous code in the diff. But if we only want to pass on args that excoveralls doesn't use, something along those lines may be best.
