### ISSUE TITLE
Empty clause not ignored

### ISSUE THREAD

**Issue by safwankamarrudin** [parroty/excoveralls#52]
I'm getting a weird issue where an empty clause for a function with a default value and multiple clauses is considered "uncovered" by the library. 

My code looks as follows.

```elixir
  def verify(_, _, verifier \\ SomeVerifier)
  def verify(_signed_token, [], _verifier), do: {:error, :invalid_token_signature}
  def verify(signed_token, [public_key | rest], verifier) do
    try do
      case verifier.verify_strict(public_key, ["RS256"], signed_token) do
        {true, %{fields: claims}, _} -> {:ok, claims}
        _ -> verify(signed_token, rest, verifier)
      end
    rescue
      MatchError -> {:error, :invalid_token}
    end
  end
```

For some reason excoveralls thinks the first line isn't covered. I know I can work around the issue by using nested case statements or "indirecting" the recursive function by calling a private one (e.g. `do_verify`), but I prefer not to do any of that.

Any idea?

**Comment by parroty** [comment]
Thanks for the report. I think it's same issue as #49. ExCoveralls internally uses erlang's `cover` module and may need some trick, but haven't been able to find a good one yet.

**Comment by parroty** [comment]
Closing at the moment, in favor of #49 as it's same/similar issue.
