### ISSUE TITLE
mix coveralls.travis command not found

### ISSUE THREAD

**Issue by es1o** [parroty/excoveralls#58]
I'm trying to run mix coveralls.travis command but I've got a error:
```
~/work/esioci(branch:master) » mix coveralls.travis                                     
** (Mix) The task "coveralls.travis" could not be found
```

I use sample .travis.yml from this repository: https://github.com/parroty/coverage_sample

**Comment by parroty** [comment]
Hi, how the `deps` section of `mix.exs` is defined to import `excoveralls`? If it's defined only for `test` environment, it may require to use `MIX_ENV=test`.

```sh
MIX_ENV=test mix coveralls.travis
```

The following is another example.
https://github.com/parroty/extwitter/blob/master/mix.exs

**Comment by es1o** [comment]
It works! Thank you very much!

**Comment by parroty** [comment]
Thanks for the update
