### ISSUE TITLE
Support for Codecov.io

### ISSUE THREAD

**Issue by nathany** [parroty/excoveralls#62]
It would be great if ExCoveralls also supported @stevepeak's Codecov.
https://codecov.io

I'm trying to figure out how to send him some JSON. #61

**Comment by parroty** [comment]
Thanks for the feedback. I wasn't aware of the site, and it would be great to support the format.
I may be looking into further, but PR would be great too :-)

**Comment by idyll** [comment]
I will open a PR for it in the next day or so. They just need the JSON file output from verbose mode dumped out.

**Comment by stevepeak** [comment]
@nathany provided us a json output (see below) which we will write a server side processor for. I expect to have this complete by tonight. Thanks @nathany 👍  

------

@idyll my recommendation for your pr would be to show of the technique for dumping the json data into a file so [Codecov bash](https://github.com/codecov/codecov-bash) uploader can pick it up. We use this bash uploader for over 80% of languages, helping with support and ease of integration.

```sh
# something like
mix test --cover > coveage.json
bash <(curl -s https://codecov.io/bash)
```
> codecov will automatically detect CI, collect all report and upload them to Codecov. There are many other tricks behind this process that help us integrate with the repository [learn more here](https://github.com/codecov/codecov-bash)

#### JSON examples
> reduced for essentials only

```json
{
  "source_files": [
    {
      "name": "path/to/file.ex",
      "coverage": [
        null,    //line-1
        35       //line-2
      ]
    }
}
```

> PS. Codecov **does not** need source code, we never store it and get it from GH on the fly.

**Comment by stevepeak** [comment]
I've added the server side processing for coveralls-json files. 👍

**Comment by nathany** [comment]
@parroty Do you have any suggestions on how to best support Codecov as an option?

**Comment by stevepeak** [comment]
I would be more then happy to help out with how to use the upload endpoint.  The easiest way to describe this is reviewing our [Ruby uploader](https://github.com/codecov/codecov-ruby), which is very straight forward. But to be honest... I highly suggest writing the json file to disk and have [Codecov Bash](https://github.com/codecov/codecov-bash) do the rest == easy-peezy

**Comment by stevepeak** [comment]
Tapping this issue again. We have support for coveralls.json files in Codecov servers side and are ready for uploads. 

@nathany do you know a way to output the json file so codecov-bash can pick it up?

**Comment by nathany** [comment]
I haven't looked into yet myself, but @idyll has a good idea. 

Basically we need to add a mix task that just outputs the appropriate JSON.

**Comment by stevepeak** [comment]
Is there anything I can do to help this issue out?

**Comment by parroty** [comment]
I'm sorry I haven't being able to look into the details yet, and will try to.

**Comment by nathany** [comment]
Since `mix coveralls.html` generates `cover/excoveralls.html`, how about `mix coveralls.json`  generates `cover/excoveralls.json`?

**Comment by nathany** [comment]
I've tested this with #71 and it works:

```console
MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

bash <(curl -s https://codecov.io/bash) -f cover/excoveralls.json -r user/repo
```

**Comment by stevepeak** [comment]
@nathany I'll add `excoveralls.json` to out automatically detected reports. The result will allow

```diff
- bash <(curl -s https://codecov.io/bash) -f cover/excoveralls.json -r user/repo
+ bash <(curl -s https://codecov.io/bash)
```
> the `-r` is an issue I'll resolve too.

**Comment by JoshSmith** [comment]
@nathany can this be closed now?

**Comment by nathany** [comment]
yup.

currently building out an example of using codecov here: https://github.com/codecov/example-elixir
