### ISSUE TITLE
Failed to upload the report to 'https://coveralls.io' (reason: timeout).

### ISSUE THREAD

**Issue by victorlcampos** [parroty/excoveralls#65]
Hi,
i'm trying use this with travis but I'm getting this error. Could you help me?

The repo is visagio/visag(https://github.com/visagio/visag),
and here the build error: https://travis-ci.org/visagio/visag

**Comment by sobolevn** [comment]
Having the same issue:
https://travis-ci.org/elixir-lang-moscow/site/builds
https://coveralls.io/github/elixir-lang-moscow/site?branch=master

**Comment by fcevado** [comment]
I had this same problem yesterday, but today is working fine. I suppose it's a problem between travis and coveralls, not related with excoveralls.

**Comment by parroty** [comment]
Thanks for the reports and helps. Please let me close as tentative timeout error between travis and coveralls.io as mentioned above (assuming it's not occurring now).

**Comment by ramondelemos** [comment]
Hi, I'm facing this same problem now.

https://travis-ci.org/ramondelemos/tech-challenge/jobs/389513128

I guess that it's problem is between Travis CI and Coveralls.io. Someone can help me?
