### ISSUE TITLE
.eex template error: no function clause matching in Enum.reverse_slice/3

### ISSUE THREAD

**Issue by kipcole9** [parroty/excoveralls#67]
`coveralls 0.5.5` on `Erlang/OTP 19` for `mix coveralls.html` results in:
```
** (FunctionClauseError) no function clause matching in Enum.reverse_slice/3
    (elixir) lib/enum.ex:1864: Enum.reverse_slice(["cldr.ex", "lib"], 1, #Function<3.4269533/1 in ExCoveralls.Html.View.render/1>)
    lib/templates/html/htmlcov/coverage.html.eex:17: anonymous fn/2 in ExCoveralls.Html.View.render/1
```
The offending line is in `coverage.html.eex`:
```
<% [b | s] = String.split(file.filename, "/") |> Enum.reverse |> Enum.reverse_slice(1, &(&1.length)) %>'
```
Here the code is calling `Enum.reverse_slice(["path", "components"], 1, &(&1.length))` which doesn't make sense to me since the third argument should be a `count` which should be an integer.  I assume the intent is to dynamically determine the length of the list in the first argument, but this code doesn't do that.

## Possible fix

Change line 17 to: 
```
<% parts = String.split(file.filename, "/") %>
<% [b | s] = parts |> Enum.reverse |> Enum.reverse_slice(1, Enum.count(parts))%>
```
This appears to work (in my system).

**Comment by parroty** [comment]
Thanks for the report. Does the above fix matches your expectation? I tried to simulate the same error, but I haven't been able to yet (though your comment makes sense).
(line is tweaked for avoiding the test error with minimum change).

**Comment by kipcole9** [comment]
I have a few `:extras` configured in a subdirectory of the app which is I think what triggers the error.  For example my `mix.exs` contains a function to return the extra files:
```elixir
  @doc_dir "./guides"
  defp extra_docs do
    @doc_dir
   |> File.ls!
   |> Enum.map(&Path.join(@doc_dir, &1))
  end
```
The error would only be triggered if there are more than one path components in a file and I guess thats not common.  Let me re-run my tests on `master` and confirm but it looks good to me.

Many thanks.

**Comment by kipcole9** [comment]
Confirmed the patch fixes the issue i was seeing.

**Comment by parroty** [comment]
Thanks, pushed as v0.5.6.
