### ISSUE TITLE
Coveralls Badge only Displays Last App Tested in Umbrella App

### ISSUE THREAD

**Issue by andrewcottage** [parroty/excoveralls#76]
When displaying the coveralls badge we cannot get the badge to display the overall combined test percentage for the entire umbrella app. It is only displaying the last application that was tested.

Now when we run `mix coveralls -u` from the command line we get a combined test coverage percentage as we expected.

Has anyone else had this issue? Any input is greatly appreciated.

**Comment by hdalssaso** [comment]
Same issue here...
