### ISSUE TITLE
Files with 0 lines should have 100% coverage by default

### ISSUE THREAD

**Issue by hauleth** [parroty/excoveralls#87]
Currently it reports that such files have 0% coverage.

**Comment by JoshSmith** [comment]
This is an interesting problem. I would think that even though there are zero executable lines of code, it's still _technically_ correct to say that there is 0% coverage of that file.

What use case do you have where you have a completely empty file in your project?

**Comment by hauleth** [comment]
For example (almost) default Phoenix `Repo` module

```elixir
defmodule MyApp.Repo do
  use Ecto.Repo, otp_app: :my_app

  @dialyzer {:nowarn_function, rollback: 1}
  @dialyzer {:nowarn_function, insert_or_update: 2}
  @dialyzer {:nowarn_function, insert_or_update!: 2}
end
```

Which has no unused lines and no used lines (even if it is used during tests). I believe that in such case (0 SLOC and 0 covered lines) there should be automatically 100% coverage.

**Comment by JoshSmith** [comment]
Thanks, that's a good example!

**Comment by parroty** [comment]
Thanks for the feedback. 
There was related item (https://github.com/parroty/excoveralls/pull/7 has some description). What do you think about applying the option in `coveralls.json`?

**Comment by hauleth** [comment]
I think that this can be used as a temporary workaround, but it should be default behaviour.

**Comment by parroty** [comment]
OK, understood the point. Also, I've rechecked the coveralls.io output and it seems they're taking it as 100%. I'll be changing the default to 100%.

**Comment by parroty** [comment]
Thanks for the comment and sorry being late to respond. I'm closing by pushing as v0.6.0, but if you find further issue/comment, please reopen.
