### ISSUE TITLE
The Gitlab CI example link is broken.

### ISSUE THREAD

**Issue by beckler** [parroty/excoveralls#95]
Title says it all. :(

**Comment by parroty** [comment]
Thanks, it seems the project is deleted :-).

@ZJvandeWeg Do you still possibly have the definition for gitlab sample (following)? 
I would like to replicate for my account (I'm trying, having some struggle).

https://gitlab.com/zj/gitlab_sample
- https://github.com/parroty/excoveralls/commit/6696de7ad1ec25168efa08352aee3e092bc7f668

**Comment by parroty** [comment]
I think I could make it work (with the help of GitLab documents). Sorry and thanks.

**Comment by ZJvandeWeg** [comment]
My bad, let me check if I can retrieve it :)

**Comment by parroty** [comment]
I've tried to replicate in the following.
- https://gitlab.com/parroty/gitlab_sample
It seems working fine, but if something is missing please let me know.

**Comment by ZJvandeWeg** [comment]
Seems correct. Thanks!

**Comment by beckler** [comment]
Thank you @parroty and @ZJvandeWeg!
That was a wicked fast resolution!
