### ISSUE TITLE
Coverage ran on the command line reports nothing

### ISSUE THREAD

**Issue by nwlucas** [parroty/excoveralls#97]
When I run `mix covrealls` or `mix coveralls -u`, I get nothing reported on the command line for coverage event though it runs though the tests

mix.exs in the root of the umbrella project:
```
defmodule TuxSentry.Mixfile do
  use Mix.Project

  def project do
    [apps_path: "apps",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps(),
     test_coverage: [tool: ExCoveralls],
     preferred_cli_env: [
      "coveralls": :test,
      "coveralls.detail": :test,
      "coveralls.post": :test,
      "coveralls.html": :test
      ],
     dialyzer: [
      plt_add_deps: :transitive,
      paths: [
        "_build/dev/lib/facts/ebin",
        "_build/dev/lib/core/ebin",
        "_build/dev/lib/ui/ebin",
      ]
     ]
    ]
  end

  defp deps do
    [
      {:dialyxir, "~> 0.5.0", only: [:dev]},
      {:excoveralls, "~> 0.6", only: :test}
    ]
  end
end
```

Sample output from the root of the umbrella project:
![image](https://cloud.githubusercontent.com/assets/4689066/24088304/44936aa0-0cff-11e7-8b52-b83a8e9e6d22.png)

Since I am new to Elixir and Erlang, it is very possible I am missing something entirely to cause this and would appreciate any pointers or help.

Side note:
When I run coverage to generate html files it is placed in a cover folder of each sub app for all apps. I was surprised to see html files for sub app 1 in sub app 2 and sub app 3 and so on, it seemed repetitive. Is this the expected behavior or another configuration that I missed somewhere?

**Comment by sashaafm** [comment]
👍  same issue here

**Comment by parroty** [comment]
Thanks for the report. I've updated the following example with excoveralls `v0.6.3` and checking the behavior. For this example, it seems the coverage is reported (tested with elixir `v1.2.6` and `v1.4.2`). I've locally added `dialyzer` for just in case, but couldn't see difference.
- https://github.com/parroty/excoveralls_umbrella

> When I run coverage to generate html files it is placed in a cover folder of each sub app for all apps.

For the above example, it's output in each subapp by default, and under top directory if `-u (--umbrella)` option is specified.

Do you see any major difference from above example?

@sashaafm If you find any insight about the condition, it would be great too.

**Comment by nwlucas** [comment]
Ahh that's the difference. FWIW I assumed that by adding the following `test_coverage: [tool: ExCoveralls],` to the root mix.exs it would automatically work for all sup apps but in the example you provided it is also listed in each sub app's mix.exs.

After adding it now the command line reports coverage as expected.

Also thank you for the pointer about the mechanisms for the generated html reports. Now that I know it wouldn't be a surprise anymore. Is there an option or configuration that I can use to force it /cover of the root application always regardless of what flag is used at invocation?
